targets:
  $default:
    builders:
      freezed|freezed:
        generate_for:
          - lib/**/*.dart
      json_serializable|json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          - lib/**/*.dart
