// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAlam_e0ZPgwAolzvFq2c2eJSMMpuhnE',
    appId: '1:867599713553:android:e6b7dac9110343f0d0f8b0',
    messagingSenderId: '867599713553',
    projectId: 'rescupaws',
    storageBucket: 'rescupaws.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfUU6WriJHvu3Z27y9YeN-h6I2FGytUvM',
    appId: '1:867599713553:ios:7e6804be1b34b7c9d0f8b0',
    messagingSenderId: '867599713553',
    projectId: 'rescupaws',
    storageBucket: 'rescupaws.firebasestorage.app',
    iosBundleId: 'io.devopen.rescupaws',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4fTlI_6NRWzTTgd5wxXTPc7Nn2B2m4A',
    appId: '1:867599713553:web:a078d5c13753f294d0f8b0',
    messagingSenderId: '867599713553',
    projectId: 'rescupaws',
    authDomain: 'rescupaws.firebaseapp.com',
    storageBucket: 'rescupaws.firebasestorage.app',
  );

}