# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

FASTLANE_USER="canayunus@gmail.com"
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="yctq-ndls-crtj-boon"


default_platform(:ios)

platform :ios do
 desc "Runs all the tests"
 lane :test do
   cocoapods(
     podfile: "../ios/Podfile"
   )
   scan(
     workspace: "../ios/Runner.xcworkspace",
     scheme: "Runner"
   )
 end

 desc "upload to TestFlight track"
 lane :upload_to_testflight do   
   build_number = number_of_commits()
   Dir.chdir "../.." do 
     sh("flutter", "build", "ios", "--release", "--build-number=#{build_number}") 
   end 
   Dir.chdir "../.." do 
    sh("flutter", "build", "ipa", "--build-number=#{build_number}") 
  end 
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "yctq-ndls-crtj-boon"
  upload_to_testflight(skip_waiting_for_build_processing: true, ipa: "../build/ios/ipa/patipati.app.ipa")
  end

  desc "to testflight"
  lane :testflight do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "yctq-ndls-crtj-boon"
    upload_to_testflight(skip_waiting_for_build_processing: true, ipa: "../build/ios/ipa/patipati.app.ipa", uses_non_exempt_encryption: true)
  end
end

