default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "upload Playground APK to alpha track"  
  lane :upload_APK_Playground do    
    build_number = number_of_commits()
    Dir.chdir "../.." do 
      sh("flutter", "build", "appbundle", "--release", "--build-number=#{build_number}") 
    end 
    upload_to_play_store(      
      package_name:               'app.patipati',      
      track:                      'alpha', #beta, production   
      json_key_data:              ENV['googlePlayJsonKey'],      
      aab:                        '../build/app/outputs/bundle/release/app-release.aab',      
      skip_upload_apk:            'false',      
      skip_upload_metadata:       'true',      
      skip_upload_images:         'true',      
      skip_upload_screenshots:    'true',      
      validate_only:              'false',      
      check_superseded_tracks:    'false',    
    )  
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(     
      package_name:               'app.patipati',      
      track:                      'alpha', #beta, production   
      json_key_data:              ENV['googlePlayJsonKey'],      
      aab:                        '../build/app/outputs/bundle/release/app-release.aab',      
      skip_upload_apk:            'false',      
      skip_upload_metadata:       'true',      
      skip_upload_images:         'true',      
      skip_upload_screenshots:    'true',      
      validate_only:              'false',      
      check_superseded_tracks:    'false',    
    )
  end
end


