# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "upload Playground APK to alpha track"  
  lane :upload_APK_Playground do    
    Dir.chdir "../.." do 
      sh("flutter", "build", "appbundle", "--release") 
    end 
    upload_to_play_store(      
      package_name:               'app.patipati',      
      track:                      'alpha', #beta, production   
      json_key_data:              ENV['googlePlayJsonKey'],      
      apk_paths:                  '../build/app/outputs/bundle/release/app-release.aab',      
      skip_upload_apk:            'false',      
      skip_upload_metadata:       'true',      
      skip_upload_images:         'true',      
      skip_upload_screenshots:    'true',      
      validate_only:              'false',      
      check_superseded_tracks:    'false',    
    )  
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end


